/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_EP_SCHEDULE: string
  readonly VITE_EP_RETRIEVE: string
  readonly VITE_EP_REMOVE: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}